### ISSUE TITLE
DAO Test Issues...

### ISSUE THREAD

**Issue by SteveFeldman** [jshipper/acled-conflict-visualization#6]
Hi Jay,

I was able to get the project up and running with a -DskipTests, however I am getting this fairly simple error when attempting to run mvn clean install. Looks like a simple/quick fix...

Mon Jan 18 20:16:22 UTC 2016 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 1.894 sec <<< FAILURE!

Results :

Tests in error: 
  com.jshipper.acled.dao.ConflictDaoImplTest: Error calling Driver#connect
  com.jshipper.acled.dao.ConflictDaoImplTest

Tests run: 2, Failures: 0, Errors: 2, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] acled-data-visualization .......................... SUCCESS [4.761s]
[INFO] acled-data-visualization-model .................... SUCCESS [12.700s]
[INFO] acled-data-visualization-dao ...................... FAILURE [5.023s]
[INFO] acled-data-visualization-rest-services ............ SKIPPED
[INFO] acled-data-visualization-ui ....................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 22.706s
[INFO] Finished at: Mon Jan 18 20:16:23 UTC 2016
[INFO] Final Memory: 18M/43M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.10:test (default-test) on project acled-data-visualization-dao: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/vagrant/projects/acled-conflict-visualization/dao/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :acled-data-visualization-dao

**Comment by jshipper** [comment]
@SteveFeldman Just took a quick look.  I hard-coded the Hibernate connection properties in the ConflictDaoImplTest class.  I'll change it to read the properties from a file, so that they can easily be changed for a given environment, just as with the rest-services module.  Sorry about that.

**Comment by jshipper** [comment]
@SteveFeldman Pushed a commit that addresses this issue.  You just need to update the `test-app.properties` file (in `dao/src/test/resources`) to connect to your MySQL instance.  Let me know if you are still having an issue building the project with the tests.

**Comment by jshipper** [comment]
@SteveFeldman , did my change and the above instructions address this issue for you, or is the build still not working?
